### ISSUE TITLE
sbt-jni ignores sbt "-java-home" option

### ISSUE THREAD

**Issue by hansjoergschurr** [jodersky/sbt-jni#14]
On my, and multiple other system I encountered, both Java 7 and 8 are installed. Our project depends on Java 8. To compile the project with sbt the "-java-home" command line option can be used like so:

> sbt -java-home /usr/lib/jvm/java-8-openjdk-amd64/ compile

Unfortunately this does not work with `nativeCompile`:

> sbt -java-home /usr/lib/jvm/java-8-openjdk-amd64/  nativeCompile
> [info] Loading global plugins from /home/user/.sbt/0.13/plugins
> [info] Loading project definition from /home/user/P/project
> [info] Set current project to Leo III (in build file:/home/user/P/)
> [error] CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
> [error]   Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
> [error]   JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
> [error] Call Stack (most recent call first):
> [error]   /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
> [error]   /usr/share/cmake-2.8/Modules/FindJNI.cmake:251 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
> [error]   CMakeLists.txt:21 (find_package)
> [error] 
> [error] 
>  java.lang.RuntimeException: Building native library failed. Exit code: 1
> 	at scala.sys.package$.error(package.scala:27)
> 	at ch.jodersky.sbt.jni.build.ConfigureMakeInstall$Instance$class.library(ConfigureMakeInstall.scala:34)
> 	at ch.jodersky.sbt.jni.build.CMake$$anon$1.library(CMake.scala:16)
> 	at ch.jodersky.sbt.jni.plugins.JniNative$$anonfun$settings$7.apply(JniNative.scala:118)
> 	at ch.jodersky.sbt.jni.plugins.JniNative$$anonfun$settings$7.apply(JniNative.scala:109)
> 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
> 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
> 	at sbt.std.Transform$$anon$4.work(System.scala:63)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
> 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
> 	at sbt.Execute.work(Execute.scala:237)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
> 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
> 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> [error] (*:nativeCompile) Building native library failed. Exit code: 1
> [error] Total time: 0 s, completed Oct 5, 2016 10:52:13 AM

Using `update-alternatives` to set the Java version works fine, but requires root privileges and is therefore not always a feasible alternative.

**Comment by jodersky** [comment]
It looks like CMake isn't picking up the location of the jni header files. Can you try running sbt in an environment that has JAVA_HOME set to the appropriate location? Something like `JAVA_HOME=<path-to-jdk-home> sbt`

**Comment by hansjoergschurr** [comment]
This works. Thank you! 

To get `sbt compile` to work in this scenario, one has to set `PATH` to `$JAVA_HOME/bin:$PATH` too. I wonder if setting `JAVA_HOME` for `cmake` to `-java-home` wouldn't be a more consistent semantic.

**Comment by jodersky** [comment]
> I wonder if setting JAVA_HOME for cmake to -java-home wouldn't be a more consistent semantic.

I totally agree, in fact I'm surprised that CMake didn't pick up the custom JAVA_HOME and JNI header files. What happens if you export the new java home before running `sbt compile`?
I'm suspecting that the customizations aren't forwarded through the sbt plugin

**Comment by hansjoergschurr** [comment]
I'm not sure if I understand you correctly. I now tried this:
> export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
> export PATH=$JAVA_HOME/bin:$PATH
> sbt compile
> sbt nativeCompile
and it works well.

**Comment by jodersky** [comment]
great that it works! I wasn't very clear on my previous response. What I meant to say is that sbt plugins cannot pick up the "-java-home" option (only sbt's launch script knows about that), so exporting JAVA_HOME will be required.
Does it also work on you setup if you only export JAVA_HOME, without setting a new PATH? It's a minor detail, but IIRC CMake should automatically pick up the new java commands automatically.

**Comment by hansjoergschurr** [comment]
Yes, only exporting JAVA_HOME works for `nativeCompile`. 
It's required for `compile` though.

**Comment by jodersky** [comment]
Do you consider this issue resolved? The PATH requirement for sbt is out of the control of this project.

**Comment by hansjoergschurr** [comment]
Yes it is, thank you.
