### ISSUE TITLE
Unresolved dependency: What does "<latest version>" refer to?

### ISSUE THREAD

**Issue by bluenote10** [jodersky/sbt-jni#19]
Simply adding
    
     addSbtPlugin("ch.jodersky" % "sbt-jni" % "<latest version>")

to `project/plugins.sbt` results in:

    sbt.ResolveException: unresolved dependency: ch.jodersky#sbt-jni;<latest version>: not found

What does "\<latest version\>" refer to? Was searching around, but I can find it (only this, but that does not seem to work either: `version in ThisBuild := ("git describe --always --dirty --match v[0-9].*" !!).tail.trim`)

Or is this actually supposed to work and it is an issue with the Maven repository? Because I can't see it [here](https://mvnrepository.com/artifact/ch.jodersky).

**Comment by bluenote10** [comment]
Oh, got it, today is my blind day: It's 1.2.5 (it is in the bintray icon).

**Comment by jodersky** [comment]
Correct, I should mention to look at the bintray badge in the README.

I'm implementing a direct push-to-deploy mechanism, whereby pushing an annotated git tag will automatically build and publish the project. IMO, continuous deployment should not change source code, hence the version cannot automatically be replaced in the readme and therefore I removed the explicit version string and replaced it with a '<latest version>' placeholder
