### ISSUE TITLE
Packaging for multiple platforms

### ISSUE THREAD

**Issue by eaplatanios** [jodersky/sbt-jni#21]
Is there currently a way to package the native library for multiple platforms?

For example, I have some JNI bindings that compile on both Linux and Mac and I want to create and publish separate packages for each platform so someone can later add to his/her SBT dependencies the package matching their platform.

Thank you!

**Comment by jodersky** [comment]
I reckon that the simplest solution to this would be to have different sbt projects per platform: a main project and for every supported platform a different subproject.

With that approach, it would even be possible to generate the name of the project dynamically, in case the project is not set up for cross-compilation. E.g. `val proj = (project in file("...")).settings(name := $(uname))`

**Comment by eaplatanios** [comment]
Even in this case though, how would you specify to sbt-jni that a particular project needs to be compiled for a specific platform/architecture?

**Comment by jodersky** [comment]
You could override the [platform setting](https://github.com/jodersky/sbt-jni/blob/master/plugin/src/main/scala/ch/jodersky/sbt/jni/plugins/JniNative.scala#L18) that is used for packaging `(nativePlatform := "...")`.

**Comment by jodersky** [comment]
Note that this only informs the native build tool where to output libraries. In case you want to support cross-compilation, you'd still need to somehow tell the tool which platform it is targeting (that would be dependent on the native build tool)
