### ISSUE TITLE
Sbt 1.0 support

### ISSUE THREAD

**Issue by TimothyKlim** [jodersky/sbt-jni#22]
Sbt 1.0 was released https://github.com/sbt/sbt/releases/tag/v1.0.0 and it would be awesome if `sbt-jni` will support it.

**Comment by jodersky** [comment]
I'm working on this in the branch 'sbt-1'. It's almost ready to be released, however I may have encountered an issue in sbt sbt/sbt#3425 that will require a workaround.

**Comment by jodersky** [comment]
sbt 1.0.0 support is available in version 1.3.0-M1, or from a local build of the sbt-1 branch.
Once sbt fixes the issue above, I'll merge the changes into master.

**Comment by jodersky** [comment]
workaround fixed with an upgrade to sbt 1.0.1, used in version 1.3.0
