### ISSUE TITLE
Add support for JDK 10

### ISSUE THREAD

**Issue by Glavo** [jodersky/sbt-jni#28]
[javah tool has been removed in JDK 10](http://openjdk.java.net/jeps/313), I think this plugin needs to use other ways to generate JNI header files.

**Comment by jodersky** [comment]
I wasn't aware of that, thanks for reporting the issue.
It looks like the new method to generate headers is with `javac -h`. This may be tricky to use with Scala files as javac expects Java source files. Previously we could just pass compiled ".class" to `javah`.

**Comment by jodersky** [comment]
I posted [a question on stackoverflow](https://stackoverflow.com/questions/49506237/generate-jni-header-files-for-class-files-in-jdk-10). Any help would be greatly appreciated.

**Comment by jodersky** [comment]
Also related: https://stackoverflow.com/questions/48816188/kotlin-replacement-for-javah

**Comment by Glavo** [comment]
I think we can use ASM to implement a simple header file generator

**Comment by jodersky** [comment]
That does indeed look like the most viable approach atm

**Comment by Glavo** [comment]
I am trying to implement it now

**Comment by Glavo** [comment]
https://github.com/Glavo/gjavah 
You can try using this library to generate header files. I am migration it to Scala

**Comment by jodersky** [comment]
That library looks really great! I'd like to adapt it to Scala and include it in sbt-jni if possible. Under what license is it available?

**Comment by Glavo** [comment]
I added MIT license to this library.

**Comment by kammoh** [comment]
Any updates on this?

**Comment by lucaskanashiro** [comment]
Any news?

**Comment by jodersky** [comment]
Please feel free to port Glavo's gjavah to Scala and submit a PR

**Comment by Glavo** [comment]
Currently gjavah is just a simple prototype, I will re-implement and submit a PR recently.

**Comment by jodersky** [comment]
Closed by #33

**Comment by Glavo** [comment]
Sorry, I forgot about the issue. gjavah is just a prototype I made in a short time, it ignores a lot of things, I will fix these issues and open a pull request.

**Comment by jodersky** [comment]
Don't worry, your changes have already been incorporated by @kammoh in the mentioned PR. Thanks for creating gjavah!
