### ISSUE TITLE
sbt javah cannot find Scala library

### ISSUE THREAD

**Issue by suriyanto** [jodersky/sbt-jni#4]
When running sbt javah I got the following error: `Error: Class scala.Product could not be found`.

The native code:
```
  @native
  def calculate(input: InputData): CalculationResult
```

My `build.sbt`:

```
name := "test"

version := "1.0"

scalaVersion := "2.10.6"

disablePlugins(JniLoad)
```

`project/plugins.sbt`:

`addSbtPlugin("ch.jodersky" % "sbt-jni" % "1.0.0-RC1")`

Looks like there when javah was run, it's not looking at scalalibrary in the classpath. Is there anything needs to be added to the build.sbt?

**Comment by jodersky** [comment]
I removed the scala classpath from javah because I was encountering chicken-and-egg problems when a single project used both JniJavah and JniPackage. I didn't think javah required it :(
