### ISSUE TITLE
Default cmake build isn't release

### ISSUE THREAD

**Issue by aishfenton** [jodersky/sbt-jni#7]
*cmake* ideally wants you to pass the build type as an argument when calling it. Currently a release type isn't passed, so it uses whatever cmake does by default. 

I'm not sure what that default behavior is in cmake, but for my case passing doing the following manually:
```
cmake -DCMAKE_BUILD_TYPE=Debug" 
```
Made by executable 500% faster.

Ideally this would be a config option? But probably a good idea to make default behavior RELEASE.

**Comment by jodersky** [comment]
Thanks for reporting this. I agree with adding a "Release" default as well as making it configurable, however I do not want sbt to interfere with the native build configuration beyond what is strictly required. IMO, configuration of how to build the native library should be described in the native build tool and only there, that way it can also be invoked directly from the user without any surprises.

My counter-proposition is to pass a special flag to cmake, lets say "-DSBT:BOOLEAN=true", and let CMakeLists handle it accordingly, for example by setting a CMAKE_BUILD_TYPE=Release.

Would that work out?

**Comment by jodersky** [comment]
Hmm, I just read some online discussions on setting `CMAKE_BUILD_TYPE` in the CMakeLists file itself, it seems rather complicated.
I think the best solution is to just add -DCMAKE_BUILD_TYPE=Release to the sbt build, we can revisit configuration when it is required.

**Comment by aishfenton** [comment]
Thanks! Yes agree ideally it would be nicer in CMakeFile itself (and you can do it, but it's a bit ugly).
